// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykvientogdpuynzvoqzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrdmllbnRvZ2RwdXluenZvcXpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NzQ0MzQsImV4cCI6MjA2MjQ1MDQzNH0.DtFcPBkos3cdkTXM4-TjrkPrnHIBtJ_Q_mRjy9767Wk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);